-- AlterEnum: CONSUMER/SCIENCE -> PACK/FORMULATION
ALTER TYPE "LabType" RENAME TO "LabType_old";
CREATE TYPE "LabType" AS ENUM ('PACK', 'FORMULATION');
ALTER TABLE "Category" ALTER COLUMN "lab" DROP DEFAULT;
ALTER TABLE "Category" ALTER COLUMN "lab" TYPE "LabType" USING (
  CASE "lab"::text
    WHEN 'CONSUMER' THEN 'PACK'::"LabType"
    WHEN 'SCIENCE' THEN 'FORMULATION'::"LabType"
    ELSE 'PACK'::"LabType"
  END
);
ALTER TABLE "Category" ALTER COLUMN "lab" SET DEFAULT 'PACK';
DROP TYPE "LabType_old";
